#!/usr/bin/env bash

set -exuo pipefail

_notif() {
    echo "npm-publish: $@" 1>&2
}

_fatal() {
    _notif "[FATAL] $@"
    exit 1
}

subdir="$1"  ; shift
package="$1" ; shift

cd "$subdir"

local_version="$(cat package.json  | jq --raw-output '.version')"
published_version="$(npm view "$package" | grep 'latest' | cut --field=2 --delimiter=':' | tr -d '[:space:]')"

_notif "subdirectory: $subdir"
_notif "local version: $local_version"
_notif "published version: $published_version"

lower_version="$(echo -e "$published_version\n$local_version" | sort --version-sort | head -n 1)"
version_bumped='false'
[[ "$local_version" == "$lower_version" ]] || version_bumped='true'

changes_made='false'
merge_base_branch="${MERGE_BASE_BRANCH:-master}"
git fetch 'ssh://github.com/runtimeverification/k-web-theme' $merge_base_branch
git diff --quiet FETCH_HEAD HEAD -- ./ || changes_made='true'

if [[ "$changes_made" == 'true' ]] ; then
    _notif "Changes made to subdirectory: $subdir"
    if [[ "$version_bumped" == 'true' ]] ; then
            _notif "Version bumped: $package"
        else
            _fatal "No bump to package version number: $subdir"
    fi
else
    _notif "No changes made to subdirectory: $subdir"
    exit 0
fi

if [[ "${1:-}" == "publish" ]]; then
    _notif "Publishing!"
    npm publish
fi